name: Deploy docs-en to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_EN_PROJECT_ID }}
on:
  push:
    branches:
      - main
    paths:
      - docs/en/**
  workflow_dispatch:
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
          cache-dependency-path: docs/en/pnpm-lock.yaml
      - name: Install Vercel CLI
        run: pnpm i -g vercel@latest
      - name: Build Project and Deploy to Vercel
        working-directory: ./docs/en
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}
  DocSearch-Crawl:
    needs: Deploy-Production
    runs-on: ubuntu-latest
    steps:
      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
        id: algolia_crawler
        with:
          crawler-user-id: ${{ secrets.DOCSEARCH_DOCS_CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.DOCSEARCH_DOCS_CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.DOCSEARCH_DOCS_EN_ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.DOCSEARCH_DOCS_EN_ALGOLIA_API_KEY }}
          site-url: 'https://docs.aircode.io'
          crawler-name: aircode
